export default {
  expo: {
    // ----------------------------------------------------
    // 1. PROJECT IDENTIFIERS (MANDATORY CHANGES)
    // ----------------------------------------------------
    name: "MY-NEW-APP",
    slug: "my-new-app-slug", // <-- CHANGED for new project slug
    version: "1.0.0",
    
    // CHANGE THIS: Must be unique for deep linking
    scheme: "mynewappscheme", // <-- CHANGED
    
    // ----------------------------------------------------
    // 2. CORE SETTINGS (COPIED/RETAINED)
    // ----------------------------------------------------
    orientation: "portrait",
    icon: "./assets/images/logo.png",
    userInterfaceStyle: "automatic",
    newArchEnabled: true,

    android: {
      // MANDATORY CHANGE: Unique application ID for Android
      package: "com.yourcompany.mynewapp", // <-- CHANGED (E.g., com.yourcompany.mynewapp)
      adaptiveIcon: {
        foregroundImage: "./assets/images/adaptive-icon.png",
        backgroundColor: "#1D0A33",
      },
      edgeToEdgeEnabled: true,
      predictiveBackGestureEnabled: false,
    },

    ios: {
      // MANDATORY CHANGE: Unique bundle ID for iOS
      bundleIdentifier: "com.yourcompany.mynewapp", // <-- CHANGED (E.g., com.yourcompany.mynewapp)
      supportsTablet: true,
    },

    // ----------------------------------------------------
    // 3. PLUGINS & EXPERIMENTS (COPIED/RETAINED)
    // ----------------------------------------------------
    web: {
      bundler: "metro",
      output: "static",
      favicon: "./assets/images/favicon.png",
    },
    plugins: [
      "expo-router",
      [
        "expo-splash-screen",
        {
          image: "./assets/images/logo.png",
          imageWidth: 200,
          resizeMode: "contain",
          backgroundColor: "#1D0A33",
          dark: { backgroundColor: "#1D0A33" },
        },
      ],
    ],

    experiments: {
      typedRoutes: true,
      reactCompiler: true,
    },

    // ----------------------------------------------------
    // 4. EXTRA/EAS (MANDATORY CHANGE)
    // ----------------------------------------------------
    extra: {
      API_URL: process.env.EXPO_PUBLIC_API_URL,
      ENV: process.env.EXPO_PUBLIC_ENV,
      // CHANGE THIS: This ID must be generated by EAS for your new project!
      eas: { projectId: "YOUR_NEW_EAS_PROJECT_ID" }, // <-- CHANGED
    },
  },
};